### ISSUE TITLE
Is it possible to install & use without npm ?

### ISSUE THREAD

**Issue by 2Belette** [kiswa/SMPLog#3]
Hi,

My distrib blacklist npm, is there a way to use SMPLog without npm ?
Many thanks and good job

**Comment by kiswa** [comment]
It should be. I'll add an archive to the release with a drop-in set of built files.

What distro blacklists npm?

**Comment by 2Belette** [comment]
I just realized that I missed this one, sorry. I am on Hyperbola where npm is blacklisted. Had you made this archive available ? Would love to test it!

**Comment by kiswa** [comment]
Nope, haven't gotten around to it yet. I'll try to get it done within a week.

**Comment by 2Belette** [comment]
Fantastic thanks

**Comment by kiswa** [comment]
There is now an archive [attached to the release](https://github.com/kiswa/SMPLog/releases/tag/v0.1.0).

**Comment by 2Belette** [comment]
Many Many thanks ! 
Everything (main page / admin page) is working expect 'New Post' where I got 'javscript:' in my address bar when I click on it.
Hint : samething for Dasboard if I click on it I got the same behaviour.
Going manually to /admin/dash or /admin/post is working
I am using nginx so I have to adapt my conf, perhaps I missed something there..
